In [1]:
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
from collections import Counter
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)
x = np.array([8.093607318, 3.365731514])

In [2]:
%run PycharmProjects/kNNproject/kNNproject/kNN.py

In [3]:
kNN_classiy

<function __main__.kNN_classiy(k, X_train, y_train, x)>

In [6]:
predict_y = kNN_classiy(6, X_train, y_train, x)

In [7]:
predict_y

1

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
KNeighborsClassifier

sklearn.neighbors._classification.KNeighborsClassifier

In [12]:
kNN_classifier = KNeighborsClassifier(6)

In [16]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [17]:
kNN_classifier

KNeighborsClassifier(n_neighbors=6)

In [18]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [20]:
kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [21]:
x.shape

(2,)

In [22]:
X_train.shape

(10, 2)

In [23]:
y_train.shape

(10,)

In [24]:
x.reshape(-1, 1)

array([[8.09360732],
       [3.36573151]])

In [25]:
x

array([8.09360732, 3.36573151])

In [26]:
kNN_classifier.predict(x)


ValueError: Expected 2D array, got 1D array instead:
array=[8.09360732 3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [27]:
x = np.array([8.093607318, 3.365731514])


In [28]:
x

array([8.09360732, 3.36573151])

In [29]:
x.shape

(2,)

In [30]:
x.reshape(-1, 1)

array([[8.09360732],
       [3.36573151]])

In [31]:
x

array([8.09360732, 3.36573151])

In [32]:
x_reshape = x.reshape(-1, 1)

In [33]:
x_reshape

array([[8.09360732],
       [3.36573151]])

In [34]:
kNN_classifier.predict(x_reshape)

ValueError: X has 1 features, but KNeighborsClassifier is expecting 2 features as input.

In [35]:
x_reshape.shape

(2, 1)

In [36]:
x_reshape = x.reshape(1, -1)

In [37]:
x_reshape

array([[8.09360732, 3.36573151]])

In [38]:
x_reshape.shape

(1, 2)

In [39]:
kNN_classifier.predict(x_reshape)

array([1])

In [40]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [41]:
kNN_classifier.dir()


AttributeError: 'KNeighborsClassifier' object has no attribute 'dir'