### 测试与训练数据集分离

In [164]:
import numpy as np
import matplotlib.pyplot as plt
from math import sqrt
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
%run PycharmProjects/playML/playML/model_selection.py
X_train, X_test, y_train, y_test = train_test_split(X, y, 0.2)
%run PycharmProjects/playML/playML/kNN_function.py
kNN_clf = KNNClassifier(6)
kNN_clf.fit(X_train, y_train)
y_predict = kNN_clf.predict(X_test)
print(y_predict)
print(y_test)
print (np.sum([y_predict == y_test])/len(y_test))

[2 0 1 2 0 0 1 2 2 2 0 2 0 2 0 1 2 1 2 2 1 2 0 0 2 0 1 1 1 0]
[2 0 1 2 0 0 1 2 2 2 0 2 0 2 0 1 2 1 2 2 1 1 0 0 2 0 1 1 1 0]
0.9666666666666667


In [5]:
X.shape


(150, 4)

In [6]:
y.shape

(150,)

In [78]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [79]:
dir(y)





['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [81]:
import random

In [82]:
y_shuffle = random.shuffle(y)

In [83]:
y_shuffle

In [84]:
y

array([2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 1, 2, 2, 2, 0, 1, 0, 2, 1, 1, 1, 1,
       2, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 2,
       2, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 0, 0,
       1, 2, 1, 2, 0, 2, 1, 0, 2, 1, 2, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 2,
       2, 0, 1, 2, 2, 2, 1, 1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 2, 1, 1, 2, 1,
       2, 2, 1, 1, 0, 2, 0, 2, 2, 1, 0, 1, 2, 2, 2, 2, 1, 0])

In [85]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [87]:
shuffle_index = np.random.permutation(len(X))


In [88]:
len(X)

150

In [89]:
shuffle_index

array([ 92,  28, 100,  79, 115, 131, 109,   6,   0,  66,  90,  86,  55,
        51,  36,  64,  49,  70,  16,  14,  56,  54, 120,  74,  34,  21,
        69, 126,  13, 135,  97, 148, 119,  11,  30, 145, 143,  26, 113,
        59,  95, 118,  87, 130, 128,  53,  47, 106,  17,  57, 141,  18,
        50,  83,  44,  22, 144,  89, 149,   1,  81, 127, 125,  91,   5,
        61,  88,  99, 122,  93,   9,  33,  98,   2,  23, 133, 116, 136,
       110,  80,  72, 147, 138,  60,   3,   4,  63,  25, 101,  48,  84,
        37,  45, 104,  43,  77,  96, 132,  85,  29, 111,  75, 102,  40,
        41,  62,  67, 146, 103,   8, 139, 121, 108,  78,  82,  94, 134,
        35, 123,  46, 117,  42, 124,   7,  52,  12, 140, 142,  73,  58,
        68,  10,  31,  39, 112,  76,  15,  65,  27, 137,  38,  19,  32,
       107,  71, 129,  20,  24, 105, 114])

In [90]:
np.random.permutation(len(X))

array([147,  11,  17,   8,  47,  21, 129,  63, 141,   5,  89,  85,  33,
       107,  50,  18,  42,  45,  64,  74, 144,  55,  37,  26,  44, 139,
       114,  62, 102, 132, 112,  28,  75, 106,   2,  86,  16,   4,  79,
        71, 131, 130, 140,  60, 110,  23, 126,  38, 115, 125,  43,  76,
        35, 136,   0,  40, 134, 123,  54,   3,  13,   7,  91,  94, 109,
        29,  99, 145,  19,  84,  93, 137,  72,  69,  92, 128,  58,  98,
        82,  68,  59,  41,  20, 133,  56, 120,  83,  97,  90, 100, 127,
        70,  48, 103,  10,  73, 113,  30,  61,  95,  36, 138, 117,  87,
        96,  25,  88,   6, 142, 101,  77, 118,  32,  67, 146,  31,  57,
        12,  27, 135,  81, 122,  52, 124,   1, 108, 148,  80, 149, 121,
        14,  24,  66,  34, 104,  49,  53,  22, 111,  51,   9, 119,  78,
        65, 116, 143,  46,  15,  39, 105])

In [91]:
test_ratio = 0.2

In [92]:
test_size = int(test_ratio * len(X))

In [93]:
test_size


30

In [94]:
test_indexes = shuffle_index[:test_size]

In [95]:
test_indexes

array([ 92,  28, 100,  79, 115, 131, 109,   6,   0,  66,  90,  86,  55,
        51,  36,  64,  49,  70,  16,  14,  56,  54, 120,  74,  34,  21,
        69, 126,  13, 135])

In [96]:
shuffle_index

array([ 92,  28, 100,  79, 115, 131, 109,   6,   0,  66,  90,  86,  55,
        51,  36,  64,  49,  70,  16,  14,  56,  54, 120,  74,  34,  21,
        69, 126,  13, 135,  97, 148, 119,  11,  30, 145, 143,  26, 113,
        59,  95, 118,  87, 130, 128,  53,  47, 106,  17,  57, 141,  18,
        50,  83,  44,  22, 144,  89, 149,   1,  81, 127, 125,  91,   5,
        61,  88,  99, 122,  93,   9,  33,  98,   2,  23, 133, 116, 136,
       110,  80,  72, 147, 138,  60,   3,   4,  63,  25, 101,  48,  84,
        37,  45, 104,  43,  77,  96, 132,  85,  29, 111,  75, 102,  40,
        41,  62,  67, 146, 103,   8, 139, 121, 108,  78,  82,  94, 134,
        35, 123,  46, 117,  42, 124,   7,  52,  12, 140, 142,  73,  58,
        68,  10,  31,  39, 112,  76,  15,  65,  27, 137,  38,  19,  32,
       107,  71, 129,  20,  24, 105, 114])

In [97]:
train_indexes = shuffle_index[test_size:]

In [98]:
train_indexes

array([ 97, 148, 119,  11,  30, 145, 143,  26, 113,  59,  95, 118,  87,
       130, 128,  53,  47, 106,  17,  57, 141,  18,  50,  83,  44,  22,
       144,  89, 149,   1,  81, 127, 125,  91,   5,  61,  88,  99, 122,
        93,   9,  33,  98,   2,  23, 133, 116, 136, 110,  80,  72, 147,
       138,  60,   3,   4,  63,  25, 101,  48,  84,  37,  45, 104,  43,
        77,  96, 132,  85,  29, 111,  75, 102,  40,  41,  62,  67, 146,
       103,   8, 139, 121, 108,  78,  82,  94, 134,  35, 123,  46, 117,
        42, 124,   7,  52,  12, 140, 142,  73,  58,  68,  10,  31,  39,
       112,  76,  15,  65,  27, 137,  38,  19,  32, 107,  71, 129,  20,
        24, 105, 114])

In [99]:
len(train_indexes)

120

In [100]:
len(test_indexes)

30

In [101]:
X_train = X[train_indexes]
y_train = y[train_indexes]

In [102]:
X_test = X[test_indexes]
y_test = y[test_indexes]

In [103]:
len(X_train)

120

In [104]:
X_train.shape

(120, 4)

In [130]:
%run PycharmProjects/playML/playML/model_selection.py


In [131]:
train_test_split

<function __main__.train_test_split(X, y, test_ratio=0.2, seed=None)>

In [150]:
X = iris.data
y = iris.target
print (y)
print (len(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, 0.2, 666)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
150


In [151]:
print(y)
print(y_train)
print(y_test)


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 1 2 1 1 2 2 0 1 2 2 1 1 0 0 0 0 1 0 0 2 1 1 1 0 0 2 2 1 2 0 1 1 0 1 0
 0 2 2 2 1 1 2 2 0 1 2 0 0 2 0 2 2 0 1 0 0 0 1 1 1 0 0 2 1 2 2 2 2 0 2 2 1
 1 2 2 1 2 1 0 2 0 1 1 2 0 2 2 0 2 2 1 0 0 2 0 0 0 1 0 2 1 2 0 0 0 2 2 1 0
 0 1 0 1 1 1 1 1 2]
[1 2 1 2 0 1 1 2 1 1 1 0 0 0 2 1 0 2 2 2 1 0 2 0 1 1 0 1 2 2]


In [152]:
%run PycharmProjects/playML/playML/kNN_function.py

In [153]:
kNN_clf = KNNClassifier(6)

kNN_clf.fit(X_train, y_train)


KNN(k = 6)

In [154]:
y_predict = kNN_clf.predict(X_test)

In [155]:
y_predict

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [156]:
y_test

array([1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 2, 1, 0,
       2, 0, 1, 1, 0, 1, 2, 2])

In [157]:
result = [y_predict == y_test]

In [158]:
result

[array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True])]

In [159]:
np.sum(result)


30

### Scikit learn test train split

In [165]:
from sklearn.model_selection import train_test_split

In [169]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 100)


In [167]:
print(X_train.shape)


(120, 4)


In [168]:
print(X_test.shape)

(30, 4)
