In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
standardScaler = StandardScaler()

In [5]:
standardScaler.fit(X_train)

StandardScaler()

In [6]:
standardScaler.mean_

array([5.825     , 3.09285714, 3.68571429, 1.16428571])

In [9]:
standardScaler.scale_ #描述数据分布范围，和std_一样，只是std_这个变量名在sklearn中弃用了。


array([0.80239597, 0.4493476 , 1.75828941, 0.75543946])

In [22]:
X_train_standard = standardScaler.transform(X_train)

In [23]:
X_train_standard.shape

(112, 4)

In [24]:
X_train.shape

(112, 4)

In [25]:
X_train_standard

array([[-0.77891718,  2.24134469, -1.24309131, -1.40882992],
       [ 0.46735031, -1.98700771,  0.46311245,  0.44439602],
       [ 1.83824454, -0.42919366,  1.48683471,  0.84151586],
       [ 0.7166038 ,  0.23844092,  0.91810012,  1.50338227],
       [ 0.21809681,  0.68353065,  0.46311245,  0.5767693 ],
       [-0.77891718, -0.87428339,  0.1218717 ,  0.31202273],
       [-0.52966368,  1.35116524, -1.24309131, -1.27645664],
       [-0.65429043,  1.35116524, -1.24309131, -1.27645664],
       [-1.02817067,  0.90607551, -1.18621785, -0.74696352],
       [-1.77593116, -0.42919366, -1.29996477, -1.27645664],
       [-0.03115669, -0.87428339,  0.1218717 ,  0.04727617],
       [-0.77891718,  0.68353065, -1.29996477, -1.27645664],
       [-1.52667767,  0.68353065, -1.29996477, -1.14408336],
       [ 0.84123055,  0.23844092,  0.8043532 ,  1.10626242],
       [-0.15578344, -0.42919366,  0.29249207,  0.17964945],
       [ 0.9658573 , -0.2066488 ,  0.40623899,  0.31202273],
       [ 0.21809681, -0.

In [26]:
X_test_standard = standardScaler.transform(X_test)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [29]:
knn_clf.fit(X_train_standard, y_train)

KNeighborsClassifier(n_neighbors=3)

In [30]:
knn_clf.score(X_test_standard, y_test)

0.9736842105263158

In [31]:
knn_clf.score(X_test, y_test)

0.34210526315789475