In [3]:
a=(0, 1, 2)
a*2

(0, 1, 2, 0, 1, 2)

In [4]:
import numpy as np


In [5]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
A=[]
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
n = 1000000
L = [i for i in range(n)]

In [9]:
%%time
A=[]
for e in L:
    A.append(2*e)

CPU times: total: 15.6 ms
Wall time: 116 ms


In [10]:
%%time
A = [2*e for e in L]

CPU times: total: 0 ns
Wall time: 82.5 ms


In [11]:
L = np.arange(n)

In [12]:
L

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [13]:
%%time
A = np.array(2*e for e in L)

CPU times: total: 0 ns
Wall time: 14 ms


In [14]:
%%time
A = 2*L

CPU times: total: 0 ns
Wall time: 1.97 ms


In [15]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [16]:
A = L*2

In [17]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [18]:
A+1

array([      1,       3,       5, ..., 1999995, 1999997, 1999999])

In [19]:
A-1


array([     -1,       1,       3, ..., 1999993, 1999995, 1999997])

In [20]:
X = np.arange(1, 16).reshape(3, 5)


In [21]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
X+1


array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [23]:
X*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [24]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [25]:
X//2



array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [26]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [28]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [29]:
np.tan(X)






array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [30]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [31]:
np.power(2, X)



array([[    2,     4,     8,    16,    32],
       [   64,   128,   256,   512,  1024],
       [ 2048,  4096,  8192, 16384, 32768]], dtype=int32)

In [32]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [34]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [35]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [36]:
A=np.arange(4).reshape(2, 2)

In [37]:
A


array([[0, 1],
       [2, 3]])

In [38]:
B = np.full((2, 2), 10)

In [39]:
B

array([[10, 10],
       [10, 10]])

In [40]:
A+B

array([[10, 11],
       [12, 13]])

In [41]:
A-B

array([[-10,  -9],
       [ -8,  -7]])

In [42]:
A*B

array([[ 0, 10],
       [20, 30]])

In [43]:
A/B

array([[0. , 0.1],
       [0.2, 0.3]])

In [44]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [45]:
A.dot(B).T

array([[10, 50],
       [10, 50]])

In [46]:
C=np.full((3,3), 666)

In [47]:
C

array([[666, 666, 666],
       [666, 666, 666],
       [666, 666, 666]])

In [48]:
v=np.array([1, 2])

In [49]:
v

array([1, 2])

In [50]:
A

array([[0, 1],
       [2, 3]])

In [51]:
v+A

array([[1, 3],
       [3, 5]])

In [52]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [53]:
np.vstack([v]*2)

array([[1, 2],
       [1, 2]])

In [54]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [55]:
np.tile(v, (2, 2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [56]:
v.dot(A)

array([4, 7])

In [57]:
A.dot(v)

array([2, 8])

In [58]:
invA=np.linalg.inv(A)


In [59]:
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [60]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [61]:
X=np.arange(12).reshape(2, 6)

In [62]:
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [63]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

In [65]:
pinvX = np.linalg.pinv(X)

In [66]:
pinvX

array([[-0.23015873,  0.08730159],
       [-0.14920635,  0.06349206],
       [-0.06825397,  0.03968254],
       [ 0.01269841,  0.01587302],
       [ 0.09365079, -0.00793651],
       [ 0.17460317, -0.03174603]])

In [67]:
X.dot(pinvX)

array([[ 1.00000000e+00,  0.00000000e+00],
       [-7.77156117e-16,  1.00000000e+00]])

In [68]:
pinvX.shape()

TypeError: 'tuple' object is not callable

In [69]:
pinvX.shape

(6, 2)