## List - from Machine Learning in Action 机器学习实战 by Peter Harrington

In [1]:
jj = []

In [2]:
jj

[]

In [3]:
jj.append(1)
jj.append('zju')

In [4]:
jj

[1, 'zju']

In [5]:
jj.append("nice hat")

In [6]:
jj

[1, 'zju', 'nice hat']

In [8]:
len(jj)


3

## Dictonary 字典

In [9]:
jj = {}
jj['dog'] = 'dalmatian'

In [10]:
jj

{'dog': 'dalmatian'}

In [11]:
jj[1] = 'ZJTU'

In [12]:
jj

{'dog': 'dalmatian', 1: 'ZJTU'}

In [13]:
jj['1'] = 42

In [14]:
jj

{'dog': 'dalmatian', 1: 'ZJTU', '1': 42}

## Set 集合

In [15]:
a = [1, 2, 2, 2, 4, 5, 5]

In [16]:
a

[1, 2, 2, 2, 4, 5, 5]

In [17]:
set(a)

{1, 2, 4, 5}

In [18]:
sA = set(a)


In [19]:
sA

{1, 2, 4, 5}

In [20]:
sB = set([4, 5, 6, 7, 7])

In [21]:
sB

{4, 5, 6, 7}

In [22]:
sA - sB

{1, 2}

In [23]:
sA | sB

{1, 2, 4, 5, 6, 7}

In [24]:
sA + sB

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [25]:
sA & sB

{4, 5}

## 列表推导式 list Comprehension

In [27]:
a = [1, 2, 3, 4, 5, 5]
myList = [item * 4 for item in a]

In [28]:
myList

[4, 8, 12, 16, 20, 20]

In [29]:
myList = []
for item in a:
    myList.append(item * 4)



In [30]:
myList

[4, 8, 12, 16, 20, 20]

In [32]:
myList = [item * 4 for item in a if item > 2]

In [33]:
myList


[12, 16, 20, 20]

In [34]:
len(myList)


4

# NumPy快速入门

In [36]:
from numpy import array
mm = array((1, 1, 1))
pp = array((1, 2, 3))
mm + pp

array([2, 3, 4])

In [37]:
pp * 2

array([2, 4, 6])

In [38]:
pp ** 2

array([1, 4, 9])

In [39]:
pp[1]

2

In [41]:
jj  = array(([1, 2, 3], [1, 1, 1]))

In [42]:
jj


array([[1, 2, 3],
       [1, 1, 1]])

In [43]:
jj.shape

(2, 3)

In [44]:
jj[0]

array([1, 2, 3])

In [45]:
jj[1]

array([1, 1, 1])

In [46]:
jj[, 0]

SyntaxError: invalid syntax (1762782337.py, line 1)

In [47]:
jj[, 1]

SyntaxError: invalid syntax (2447483243.py, line 1)

In [48]:
jj[0, 1]

2

In [49]:
jj[0, 2]

3

In [50]:
a1 = array([1, 2, 3])
a2 = array([0.3, 0.2, 0.3])

In [51]:
a1 * a2

array([0.3, 0.4, 0.9])

## 矩阵操作

In [54]:
from numpy import mat, matrix

In [55]:
ss = mat([1, 2, 3])

In [56]:
ss

matrix([[1, 2, 3]])

In [58]:
mm = matrix([1, 2, 3])

In [59]:
mm

matrix([[1, 2, 3]])

In [60]:
ss+mm

matrix([[2, 4, 6]])

In [61]:
mm[0, 1]

2

In [62]:
pyList = [5, 11, 16051]

In [63]:
pyList

[5, 11, 16051]

In [64]:
mat(pyList)


matrix([[    5,    11, 16051]])

In [65]:
mm*ss

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [66]:
mm*ss.T

matrix([[14]])

In [67]:
mm.shape

(1, 3)

In [68]:
shape(mm)

NameError: name 'shape' is not defined

In [69]:
from numpy import shape

In [70]:
shape(mm)


(1, 3)

In [71]:
shape(mm.T)

(3, 1)

In [72]:
from numpy import multiply

In [73]:
multiply(mm, ss)


matrix([[1, 4, 9]])

In [74]:
dd = matrix([4, 5, 1])

In [75]:
dd.sort

<function matrix.sort>

In [76]:
dd.sort()


In [77]:
dd

matrix([[1, 4, 5]])

In [78]:
dd = matrix([4, 5, 1, 9, 7])

In [79]:
dd.argsort()

matrix([[2, 0, 1, 4, 3]], dtype=int64)

In [80]:
dd

matrix([[4, 5, 1, 9, 7]])

In [81]:
dd.mean()

5.2

In [82]:
jj

array([[1, 2, 3],
       [1, 1, 1]])

## 获取矩阵某一列


In [84]:
jj[:,1]

array([2, 1])

In [85]:
jj[:, :]

array([[1, 2, 3],
       [1, 1, 1]])

In [86]:
jj[:, 0]

array([1, 1])

In [87]:
jj[:, 2]

array([3, 1])